# Generated by Django 5.1.3 on 2024-11-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_staffs_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staffs_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staffs_name',
            new_name='staff_name',
        ),
    ]
