# Generated by Django 5.1.3 on 2024-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
