# Generated by Django 5.1.3 on 2024-11-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='members_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='members_name',
            new_name='member_name',
        ),
    ]
