# Generated by Django 5.1.3 on 2024-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_id', models.CharField(max_length=10)),
                ('products_name', models.CharField(max_length=50)),
            ],
        ),
    ]
