# Generated by Django 5.1.3 on 2024-11-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('stauts', models.CharField(max_length=10)),
            ],
        ),
    ]
