# Generated by Django 5.1.3 on 2024-11-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='stauts',
            new_name='status',
        ),
    ]
